---
name: tests YAML files

on: [push, pull_request]

jobs:
    run_yamlint:
        runs-on: ubuntu-latest
        strategy:
            max-parallel: 5
            matrix:
                os: [ubuntu-latest]
        steps:
            - name: YAML Lint
              uses: ibiqlik/action-yamllint@v3.1.0
